in-web/ViewModels/AddEntryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace in_web.ViewModels
{
    public class AddEntryViewModel
    {

        public FinancialData Data { get; set; }

        [Required(ErrorMessage = "Należy określić rodzaj wpisu")]
        [Display(Name = "Rodzaj")]
        public string DataType { get; set; }
    }
}

in-web/ViewModels/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace in_web.ViewModels
{
    public class Category
    {
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Kategoria jest wymagana")]
        [Display(Name = "Kategoria")]
        [MaxLength(30, ErrorMessage = "Nazwa kategorii nie może być dłuższa niż 30 znaków")]
        public string CategoryName { get; set; }

        [Required]
        [MaxLength(30)]
        public string Username { get; set; }
    }
}

in-web/ViewModels/MainPageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace in_web.ViewModels
{
    public class MainPageViewModel
    {
        public List<FinancialData> UpcomingSignificantExpenses { get; set; }
        public decimal TotalInc { get; set; }
        public decimal TotalExp { get; set; }
    }
}

in-web/Controllers/CategoryController.cs
using in_web.Helpers;
using in_web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace in_web.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        public async Task<IActionResult> CategoryList(string showAlert = "none")
        {
            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpResponseMessage res = await client.GetAsync("/api/category/getall");
            var content = await res.Content.ReadAsStringAsync();
            var result = JSONHelper.TryParseJson<ResponseObj<List<Category>>>(content);

            if (result == null || !res.IsSuccessStatusCode)
            {
                return RedirectToAction("Error", "Home");
            }

            result.Obj.Sort((e1, e2) => e1.CategoryName.CompareTo(e2.CategoryName));

            bool tomainpage = false;
            if(Request.Cookies["sortoptions"] == null)
            {
                tomainpage = true;
            }

            ViewBag.tomainpage = tomainpage;
            ViewBag.showalert = showAlert;
            ViewBag.title = "Lista kategorii";
            return View(result.Obj);
        }

        [HttpGet]
        public IActionResult AddCategory()
        {
            ViewBag.title = "Nowa kategoria";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCategory(Category model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.title = "Nowa kategoria";
                return View();
            }

            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpResponseMessage res = await client.PostAsync("/api/category/add", new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json"));

            if (!res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var result = JSONHelper.TryParseJson<ResponseObj<Category>>(content);
                if (result != null && result.Message == "CategoryAlreadyExists")
                {
                    ModelState.AddModelError("Error", "Wprowadzona kategoria już istnieje");
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
                return View();
            }

            return RedirectToAction("CategoryList", new { showAlert = "add" });
        }

        [HttpGet]
        public async Task<IActionResult> EditCategory(int id)
        {
            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpResponseMessage res = await client.GetAsync(string.Format("api/category/get/{0}", id.ToString()));
            var content = await res.Content.ReadAsStringAsync();
            var result = JSONHelper.TryParseJson<ResponseObj<Category>>(content);

            if (result == null || !res.IsSuccessStatusCode)
            {
                return RedirectToAction("Error", "Home");
            }

            ViewBag.title = "Edycja kategorii";
            return View(result.Obj);
        }

        [HttpPost]
        public async Task<IActionResult> EditCategory(Category model, int id)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.title = "Edycja kategorii";
                return View();
            }

            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpResponseMessage res = await client.PutAsync(string.Format("api/category/edit/{0}", id.ToString()), new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json"));

            if (!res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var result = JSONHelper.TryParseJson<ResponseObj<Category>>(content);
                if (result != null && result.Message == "CategoryAlreadyExists")
                {
                    ModelState.AddModelError("Error", "Wprowadzona kategoria już istnieje");
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
                return View();
            }

            return RedirectToAction("CategoryList", new { showAlert = "edit" });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpResponseMessage res = await client.DeleteAsync(string.Format("api/category/delete/{0}", id.ToString()));

            if (!res.IsSuccessStatusCode)
            {
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction("CategoryList", new { showAlert = "delete" });
        }

        [HttpPost]
        public async Task<IActionResult> ClearDefaultCategoryEntries(string defcat)
        {
            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpResponseMessage res = await client.DeleteAsync(string.Format("api/category/clear/{0}", defcat));

            if (!res.IsSuccessStatusCode)
            {
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction("CategoryList", new { showAlert = "clear" });
        }
    }
}

in-web/Controllers/FinancesController.cs
using in_web.Helpers;
using in_web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace in_web.Controllers
{
    [Authorize]
    public class FinancesController : Controller
    {

        public async Task<IActionResult> MainPage()
        {
            Response.Cookies.Delete("options");
            Response.Cookies.Delete("sortoptions");
            Response.Cookies.Delete("chartoptions");

            HttpClient client = APIHelper.InitializeAuth(Request);
            
            if(client == null)
            {
                return RedirectToAction("Login", "Home");
            }
            
            HttpResponseMessage res = await client.GetAsync(string.Format("api/financialdata/getall?startDate={0}&endDate={1}&total=true", DateTime.Today.AddDays(-30).ToString("d", CultureInfo.InvariantCulture), DateTime.Today.ToString("d", CultureInfo.InvariantCulture)));
            var content = await res.Content.ReadAsStringAsync();
            var result1 = JSONHelper.TryParseJson<ResponseObj<Dictionary<string, decimal>>>(content);

            if (result1 == null || !res.IsSuccessStatusCode)
            {
                    return RedirectToAction("Error", "Home");
            }

            var model = new MainPageViewModel();
            
            model.TotalInc = result1.Obj["incsum"];
            model.TotalExp = result1.Obj["expsum"];

            res = await client.GetAsync(string.Format("api/financialdata/getall?startDate={0}&endDate={1}&scope=exp&minamount=1000", DateTime.Today.ToString("d", CultureInfo.InvariantCulture), DateTime.Today.AddDays(7).ToString("d", CultureInfo.InvariantCulture)));
            content = await res.Content.ReadAsStringAsync();
            var result2 = JSONHelper.TryParseJson<ResponseObj<List<FinancialData>>>(content);

            if (result2 == null || !res.IsSuccessStatusCode)
            {
                return RedirectToAction("Error", "Home");
            }

            model.UpcomingSignificantExpenses = result2.Obj;
            model.UpcomingSignificantExpenses.Sort((e1, e2) => e1.Date.CompareTo(e2.Date));

            ViewBag.title = "Strona główna";
            return View(model);
        }


        public async Task<IActionResult> DetailView(string sortBy = "Date", string sortType = "asc", string showAlert = "none")
        {
            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            var options = OptionsHelper.GetOptions(Request, "det");

            var model = new DataViewModel();
            model.Options = options;

            HttpResponseMessage res;
            
            if (model.Options.Period == "all")
            {
                res = await client.GetAsync(string.Format("api/financialdata/getall?scope={0}", model.Options.ViewScope));
            }
            else
            {
                res = await client.GetAsync(string.Format("api/financialdata/getall?startDate={0}&endDate={1}&scope={2}", model.Options.StartDate?.ToString("d", CultureInfo.InvariantCulture), model.Options.EndDate?.ToString("d", CultureInfo.InvariantCulture), model.Options.ViewScope));
            }

            var content = await res.Content.ReadAsStringAsync();
            var result = JSONHelper.TryParseJson<ResponseObj<List<FinancialData>>>(content);

            if (result == null || !res.IsSuccessStatusCode)
            {
                return RedirectToAction("Error", "Home");
            }

            model.FinancialDataList = result.Obj;

            model.SortTypeForColumns = OptionsHelper.SortingData("Amount", "Date", "CategoryName", "Name");
            
            if (sortType != "desc" && model.SortTypeForColumns.ContainsKey(sortBy))
            {
                model.SortTypeForColumns[sortBy] = "desc";
            }

            switch (sortBy)
            {
                case "Amount":
                    model.FinancialDataList.Sort((e1, e2) => e1.Amount.CompareTo(e2.Amount));
                    break;
                case "CategoryName":
                    model.FinancialDataList.Sort((e1, e2) => e1.CategoryName.CompareTo(e2.CategoryName));
                    break;
                case "Name":
                    model.FinancialDataList.Sort((e1, e2) => e1.Name.CompareTo(e2.Name));
                    break;
                default:
                    model.FinancialDataList.Sort((e1, e2) => e1.Date.CompareTo(e2.Date));
                    break;
            }
            
            if (sortType == "desc")
            {
                model.FinancialDataList.Reverse();
            }

            var sortOptions = new SortOptions(sortBy, sortType, "det");
            string sortOptionsSerialized = JsonConvert.SerializeObject(sortOptions);
            Response.Cookies.Append("sortoptions", sortOptionsSerialized);

            model.ShowAlert = showAlert;

            ViewBag.title = "Widok szczegołowy";
            return View(model);
        }

        public async Task<IActionResult> CategoryView(string sortBy = "CategoryName", string sortType = "asc", string showAlert = "none")
        {
            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            var options = OptionsHelper.GetOptions(Request, "cat");

            var model = new DataViewModel();
            model.Options = options;

            HttpResponseMessage res;

            if (model.Options.Period == "all")
            {
                res = await client.GetAsync(string.Format("api/financialdata/getall?scope={0}&aggregate=true", model.Options.ViewScope));
            }
            else
            {
                res = await client.GetAsync(string.Format("api/financialdata/getall?startDate={0}&endDate={1}&scope={2}&aggregate=true", model.Options.StartDate?.ToString("d", CultureInfo.InvariantCulture), model.Options.EndDate?.ToString("d", CultureInfo.InvariantCulture), model.Options.ViewScope));
            }

            var content = await res.Content.ReadAsStringAsync();
            var result = JSONHelper.TryParseJson<ResponseObj<List<FinancialDataGrouped>>>(content);

            if (result == null || !res.IsSuccessStatusCode)
            {
                return RedirectToAction("Error", "Home");
            }

            model.FinancialDataGrouped = result.Obj;

            model.SortTypeForColumns = OptionsHelper.SortingData("Amount", "CategoryName");

            if (sortType != "desc" && model.SortTypeForColumns.ContainsKey(sortBy))
            {
                model.SortTypeForColumns[sortBy] = "desc";
            }

            switch (sortBy)
            {
                case "Amount":
                    model.FinancialDataGrouped.Sort((e1, e2) => e1.Amount.CompareTo(e2.Amount));
                    break;
                default:
                    model.FinancialDataGrouped.Sort((e1, e2) => e1.CategoryName.CompareTo(e2.CategoryName));
                    break;
            }

            if (sortType == "desc")
            {
                model.FinancialDataGrouped.Reverse();
            }

            var sortOptions = new SortOptions(sortBy, sortType, "cat");
            string sortOptionsSerialized = JsonConvert.SerializeObject(sortOptions);
            Response.Cookies.Append("sortoptions", sortOptionsSerialized);

            model.ShowAlert = showAlert;

            ViewBag.title = "Widok kategorii";
            return View(model);
        }

        [HttpPost]
        public IActionResult ViewRedirect(DataViewModel model)
        {
            string options = JsonConvert.SerializeObject(model.Options);
            Response.Cookies.Append("options", options);

            var sortOptions = OptionsHelper.GetSortOptions(Request);

            if(model.Options.ViewType == "cat")
            {
                if(sortOptions != null & sortOptions.ViewType == "cat")
                {
                    return RedirectToAction("CategoryView", new { sortBy = sortOptions.SortBy, sortType = sortOptions.SortType  });
                }
                return RedirectToAction("CategoryView");
            }

            if (sortOptions != null & sortOptions.ViewType == "det")
            {
                return RedirectToAction("DetailView", new { sortBy = sortOptions.SortBy, sortType = sortOptions.SortType });
            }
            return RedirectToAction("DetailView");
        }

        public IActionResult ReturnToView(string showAlert = "none")
        {
            var sortOptions = OptionsHelper.GetSortOptions(Request);

            if(sortOptions != null)
            {
                if(sortOptions.ViewType == "cat")
                {
                    return RedirectToAction("CategoryView", new { sortBy = sortOptions.SortBy, sortType = sortOptions.SortType, showAlert = showAlert });
                }
                return RedirectToAction("DetailView", new { sortBy = sortOptions.SortBy, sortType = sortOptions.SortType, showAlert = showAlert });
            }

            return RedirectToAction("DetailView", new { showAlert = showAlert });
        }

        public async Task<IActionResult> ChartView()
        {
            HttpClient client = APIHelper.InitializeAuth(Request);

            if (client == null)
            {
                return RedirectToAction("Login", "Home");
            }

            var chartOptions = OptionsHelper.GetChartOptions(Request);

            var model = new ChartViewModel();
            model.ChartOptions = chartOptions;

            HttpResponseMessage res;

in-web/Views/Finances/AddEntry.cshtml
@{
    Layout = "_Layout2";
}
@model AddEntryViewModel

@section stylesheets{
    <link href="~/lib/jqueryui/themes/base/jquery-ui.css" rel="stylesheet">
}

<div class="container" style="max-width: 500px">
    <div class="text-center pt-3">Nowy wpis</div>
    <form asp-controller="Finances" asp-action="AddEntry" method="post">

        <input hidden asp-for="Data.Username" value="@User.Claims.FirstOrDefault(claim => claim.Type == ClaimTypes.Name).Value">

        <div class="row pt-3">
            <div class="col-4">
                <label asp-for="Data.Amount" class="col-form-label"></label>
            </div>
            <div class="col-8">
                <input asp-for="Data.Amount" class="form-control" />
                <span asp-validation-for="Data.Amount" class="text-danger"></span>
            </div>
        </div>

        <div class="row pt-3">
            <div class="col-4">
                <label asp-for="DataType" class="col-form-label"></label>
            </div>
            <div class="col-8">
                <div class="row ps-3">
                    @foreach (var type in AddingHelper.DataTypeValues)
                    {
                        <div class="col-6 form-check">
                            <input type="radio" class="form-check-input" asp-for="DataType" value="@type.Key" id="Type@(type.Key)">
                            <label class="form-check-label" for="Type@(type.Key)">@type.Value</label>
                        </div>
                    }
                </div>
                <span asp-validation-for="DataType" class="text-danger"></span>
            </div>
            </div>

            <div class="row pt-3">
                <div class="col-4">
                    <label asp-for="Data.Date" class="col-form-label"></label>
                </div>
                <div class="col-8">
                    <input type="text" class="form-control text-center" id="datepicker" readonly="readonly" asp-for="Data.Date">
                    <span asp-validation-for="Data.Date" class="text-danger"></span>
                </div>
            </div>

            <div class="row pt-3">
                <div class="col-4">
                    <label asp-for="Data.Name" class="col-form-label"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Data.Name" class="form-control" />
                    <span asp-validation-for="Data.Name" class="text-danger"></span>
                </div>
            </div>

            <div class="row pt-3">
                <div class="col-4">
                    <label asp-for="Data.Description" class="col-form-label"></label>
                </div>
                <div class="col-8">
                    <textarea asp-for="Data.Description" rows="3" class="form-control" style="resize: none;"></textarea>
                    <span asp-validation-for="Data.Description" class="text-danger"></span>
                </div>
            </div>

            <div class="row pt-3">
                <div class="col-4">
                    <label asp-for="Data.CategoryName" class="col-form-label"></label>
                </div>
                <div class="col-8">
                    <select asp-for="Data.CategoryName" asp-items="@ViewBag.categories" class="form-select">
                        <option value="" disabled hidden selected>--Wybierz kategorię--</option>
                    </select>
                    <span asp-validation-for="Data.CategoryName" class="text-danger"></span>
                </div>
            </div>

            <div class="row pt-3">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary btn-sm" style="width: 200px">Dodaj</button>
                </div>
            </div>
</form>

    <div class="row pt-3">
        <div class="col text-center">
            <a class="btn btn-secondary btn-sm" asp-action="ReturnToView" asp-controller="Finances" style="width: 200px">Powrót do widoku</a>
        </div>
    </div>

</div>

@section scripts{
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/js/datepickerconf.js"></script>
    <script src="~/js/addentry.js"></script>
}

in-web/Views/Finances/CategoryView.cshtml
@{
    Layout = "_Layout3";
}

<div class="container" style="max-width: 1000px">

    <!-- Information alerts -->
    @if (Model.ShowAlert == "add")
    {
        <div class="alert alert-success alert-dismissible fade show mt-5" role="alert">
            Wpis został dodany pomyślnie.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

    <!-- Data table -->
    @if (Model.FinancialDataGrouped.Count == 0)
    {
        <div class="text-center fs-5 pt-5 pb-5">Brak danych spełniających zadane kryteria.</div>
    }
    else
    {
        if (Model.Options.Period == "all")
        {
            <div class="text-center fs-5 pt-5">Wszystkie @OptionsHelper.ViewScopeValues[Model.Options.ViewScope].ToLower() pogrupowane wg kategorii</div>
        }
        else
        {
            <div class="text-center fs-5 pt-5">@OptionsHelper.ViewScopeValues[Model.Options.ViewScope] za okres od @Model.Options.StartDate?.ToShortDateString() do @Model.Options.EndDate?.ToShortDateString() pogrupowane wg kategorii</div>
        }
            <div class="row justify-content-center">
                <table class="table mt-1" style="vertical-align: middle; max-width: 500px">
                    <thead>
                        <tr>
                            <th scope="col"><a class="text-reset text-decoration-none" asp-action="CategoryView" asp-controller="Finances" asp-route-sortBy="CategoryName" asp-route-sortType="@Model.SortTypeForColumns["CategoryName"]">Kategoria</a></th>
                            <th scope="col"><a class="text-reset text-decoration-none" asp-action="CategoryView" asp-controller="Finances" asp-route-sortBy="Amount" asp-route-sortType="@Model.SortTypeForColumns["Amount"]">Kwota</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.FinancialDataGrouped)
                        {
                            <tr>
                                <td class="border-bottom border-secondary" colspan="2"></td>
                            </tr>
                            <tr>
                                <td class="pt-3 pb-3 border-start border-bottom border-secondary">@item.CategoryName</td>
                                @if (item.Amount < 0)
                                {
                                    <td class="pt-3 pb-3 border-bottom border-end border-secondary" style="color: red;">@item.Amount</td>
                                }
                                else
                                {
                                    <td class="pt-3 pb-3 border-bottom border-end border-secondary" style="color: green;">@item.Amount</td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
    }

</div>

in-web/Views/Finances/MainPage.cshtml
@{
    Layout = "_Layout2";
}
@model MainPageViewModel

<div class="container" style="max-width: 1000px">

    <div class="text-center fw-bold fs-5 pt-3">Twoje saldo z ostatnich 30 dni</div>
    <div class="text-center pt-3">Przychody</div>
    <div class="text-center pt-1" style="color: green;"><h1>@Model.TotalInc.ToString("N2")</h1></div>
    <div class="text-center pt-3">Wydatki</div>
    <div class="text-center pt-1" style="color: red;"><h1>@Model.TotalExp.ToString("N2")</h1></div>

    <canvas id="chart" style="max-height: 100px"></canvas>

    @if (Model.UpcomingSignificantExpenses.Count == 0)
    {
        <div class="text-center fs-5 pt-5 pb-5">Brak większych wydatków zaplanowanych w ciągu najbliższych 7 dni.</div>
    }
    else
    {
        <div class="text-center fw-bold fs-4 pt-3" style="color: red;">Uwaga! W ciągu najbliższych 7 dni występują większe wydatki!</div>
        <table class="table mt-1" style="vertical-align: middle;">
            <thead>
                <tr>
                    <th scope="col">Kwota</th>
                    <th scope="col">Data</th>
                    <th scope="col">Kategoria</th>
                    <th scope="col">Nazwa</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.UpcomingSignificantExpenses)
                {
                    <tr>
                        <td class="border-bottom border-secondary" colspan="5"></td>
                    </tr>
                    <tr>
                        <td class="pt-3 border-start border-bottom-0 border-secondary" style="color: red;">@item.Amount</td>
                        <td class="pt-3 border-bottom-0">@item.Date.ToShortDateString()</td>
                        <td class="pt-3 border-bottom-0">@item.CategoryName</td>
                        <td class="pt-3 border-bottom-0">@item.Name</td>
                        <td class="pt-3 border-bottom-0 border-end border-secondary">
                            <button type="button" id="descriptionButton@(item.FinancialDataId)" class="btn btn-secondary btn-sm" data-bs-toggle="collapse" data-bs-target="#descriptionRow@(item.FinancialDataId)" aria-expanded="false" aria-controls="descriptionRow@(item.FinancialDataId)" style="width: 90px">Pokaż opis</button>
                        </td>
                    </tr>
                    <tr>
                        <td class="pt-0 pb-3 border-start border-end border-bottom border-secondary" colspan="5">
                            @if (item.Description == null)
                            {
                                <div class="collapse" id="descriptionRow@(item.FinancialDataId)">(Brak opisu)</div>
                            }
                            else
                            {
                                <div class="collapse" id="descriptionRow@(item.FinancialDataId)">@item.Description</div>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    <div class="text-center pt-3">
        <a class="btn btn-primary btn-sm" asp-action="DetailView" asp-controller="Finances" style="width: 200px;">Widok szczegółowy</a>
    </div>
    <div class="text-center pt-1">
        <a class="btn btn-warning btn-sm" asp-action="CategoryList" asp-controller="Category" style="width: 200px;">Zarządzanie kategoriami</a>
    </div>
    <div class="text-center pt-1">
        <a class="btn btn-dark btn-sm" asp-action="ChartView" asp-controller="Finances" style="width: 200px;">Widok wykresów</a>
    </div>
    <div class="text-center pt-1 pb-4">
        <form method="post" asp-action="Logout" asp-controller="Home">
            <button type="submit" class="btn btn-secondary btn-sm" style="width: 200px;">Wyloguj się</button>
        </form>
    </div>

</div>

@section scripts{
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/mainpage.js"></script>
    <script src="~/lib/Chart.js/chart.min.js"></script>
    <script>
        const ctx = document.getElementById('chart').getContext('2d');
        const inc = parseFloat("@Model.TotalInc".replace(',', '.'));
        const exp = parseFloat("@Model.TotalExp".replace(',', '.')) * (-1);
        const chart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['Przychody', 'Wydatki'],
                datasets: [{ 
                    data: [inc, exp],
                    backgroundColor: ['green', 'red']
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    }
                },
                indexAxis: 'y'
            }
        });
    </script>
}